[theme]
# Primary accent color for interactive elements.
primaryColor = "#f04488"

# Background color for the main content area.
backgroundColor = "#feffe1"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffa8db"

# Color used for almost all text.
#textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"